[bestcherish]
title = "灰常记忆"
url = "https://bestcherish.com"
entrySelector = "h1.entry-title"
titleSelector = "> a"
linkSelector = "> a"
timeout = 600

[xifudangcheno]
title = "媳妇当车模"
url = "https://club.autohome.com.cn/jingxuan/104/1/"
entrySelector = "div.pic_txt > p"
titleSelector = "> a"
linkSelector = ">a"
timeout = 600


[kisnows]
title = "抹桥的博客"
url = "https://blog.kisnows.com/"
entrySelector = "header.post-header"
titleSelector = "a.post-title-link"
linkSelector = "a.post-title-link"
timeout = 600
