[bestcherish]
title = "灰常记忆"
url = "https://bestcherish.com"
entrySelector = "h1.entry-title"
titleSelector = "> a"
linkSelector = "> a"
timeout = 600

[kisnows]
title = "抹桥的博客"
url = "https://blog.kisnows.com/"
entrySelector = "header.post-header"
titleSelector = "a.post-title-link"
linkSelector = "a.post-title-link"
timeout = 600
